window.NexoraData={stories:[
{id:'india-policy',title:'India’s new policy playbook puts manufacturing at the centre',category:'India',topic:'Politics · Government',time:'18 min ago',read:'4 min read',summary:'A sharper focus on logistics, skills and resilient supply chains is setting the tone for the next growth cycle.',source:'The Economic Times',url:'https://economictimes.indiatimes.com',tone:'gold'},
{id:'india-economy',title:'The next wave of Indian consumption is being built beyond metros',category:'India',topic:'Economy · Startups',time:'31 min ago',read:'5 min read',summary:'New brands, local language commerce and better access to credit are widening the consumer map.',source:'Mint',url:'https://www.livemint.com',tone:'lime'},
{id:'india-science',title:'India’s science missions are turning research into real-world ambition',category:'India',topic:'Science · Technology',time:'48 min ago',read:'3 min read',summary:'A generation of researchers is connecting deep science with national capability.',source:'Indian Express',url:'https://indianexpress.com',tone:'blue'},
{id:'india-sport',title:'A new generation is changing the shape of Indian sport',category:'India',topic:'Sports · Entertainment',time:'1 hr ago',read:'3 min read',summary:'Investment, audience and aspiration are expanding far beyond the usual headlines.',source:'The Hindu',url:'https://www.thehindu.com',tone:'coral'},
{id:'world-climate',title:'The climate economy is moving from promise to infrastructure',category:'World',topic:'Climate · Business',time:'12 min ago',read:'4 min read',summary:'Capital is flowing toward the grids, storage and systems that make a lower-carbon future practical.',source:'Reuters',url:'https://www.reuters.com',tone:'green'},
{id:'world-ai',title:'AI is redrawing the world’s competitive map',category:'World',topic:'AI · Global news',time:'27 min ago',read:'6 min read',summary:'Nations are balancing innovation, regulation and the infrastructure required to compete.',source:'Financial Times',url:'https://www.ft.com',tone:'violet'},
{id:'world-science',title:'A quieter revolution is under way in ocean science',category:'World',topic:'Science · Climate',time:'55 min ago',read:'3 min read',summary:'New instruments are helping researchers see the world’s largest ecosystem in startling detail.',source:'BBC News',url:'https://www.bbc.com/news',tone:'blue'},
{id:'world-sports',title:'Sport is becoming the new global cultural currency',category:'World',topic:'Sports · Culture',time:'1 hr ago',read:'4 min read',summary:'The biggest moments now travel across borders with more speed and meaning than ever.',source:'The Athletic',url:'https://www.nytimes.com/athletic',tone:'pink'},
{id:'tech-agents',title:'AI agents are finding their first truly useful jobs',category:'AI',topic:'AI · Work',time:'15 min ago',read:'5 min read',summary:'The focus has shifted from spectacle to systems that quietly remove friction from daily work.',source:'MIT Technology Review',url:'https://www.technologyreview.com',tone:'violet'},
{id:'tech-chips',title:'The chip race is becoming a design race',category:'Technology',topic:'Technology · Business',time:'39 min ago',read:'4 min read',summary:'As computing demands surge, the smartest advantage may come from more efficient architecture.',source:'Bloomberg',url:'https://www.bloomberg.com',tone:'orange'},
{id:'tech-space',title:'The new lunar economy is closer than it looks',category:'Technology',topic:'Science · Space',time:'1 hr ago',read:'3 min read',summary:'A mix of public ambition and private capital is turning the Moon into the next commercial frontier.',source:'',url:'',tone:'lavender'},
{id:'business-africa',title:'Africa’s fintech ecosystem enters its next act',category:'Business',topic:'Business · Startups',time:'22 min ago',read:'5 min read',summary:'A resilient generation of companies is building financial access around the realities of everyday life.',source:'Bloomberg',url:'https://www.bloomberg.com',tone:'green'},
{id:'business-energy',title:'Energy storage is becoming the market to watch',category:'Business',topic:'Business · Climate',time:'46 min ago',read:'4 min read',summary:'The companies solving the grid’s hardest problems are attracting a fresh wave of attention.',source:'CNBC',url:'https://www.cnbc.com',tone:'gold'},
{id:'sports-women',title:'The women’s game breaks new ground',category:'Sports',topic:'Sports · Global news',time:'2 hr ago',read:'3 min read',summary:'Record audiences and new investment are making this a landmark moment for the women’s game.',source:'The Athletic',url:'https://www.nytimes.com/athletic',tone:'pink'},
{id:'ent-film',title:'Cinema’s practical-effects revival has a bigger story',category:'Entertainment',topic:'Entertainment · Technology',time:'2 hr ago',read:'3 min read',summary:'Filmmakers are rediscovering the texture and surprise of making things for real.',source:'Variety',url:'https://variety.com',tone:'orange'}
]};
